# Generated by Django 4.1.6 on 2023-02-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
    ]
